GET http://localhost:5555/partners

###
GET http://localhost:5555/partners/6383ab1a66ef72d422529822

###
POST http://localhost:5555/partners/add-partner
Content-Type: application/json;

{
    "nama" : "Putri Citra, M. Psi.",
    "rate" : "8",
    "overview" : "Putri Citra adalah psikolog yang dapat menangani permasalahan kecemasan dan relasi.Ia yakin bahwa proses kehidupan adalah pencarian jati diri.Membicarakan kekhawatiran kita dengan seorang profesional bisa menjadi langkah yang sangat berarti.",
    "pengalaman" : "Psikolog di RS Panama 4 tahun",
    "pendidikan1" : "S-1 Psikologi Universitas Atma Jaya Yogyakarta",
    "pendidikan2" : "S-2 Psikologi Universitas Negeri Malang",
    "contact" : "089637074190",
    "img" : "https://img.freepik.com/free-photo/portrait-young-asia-lady-with-positive-expression-arms-crossed-smile-broadly-dressed-casual-clothing-looking-camera-pink-background_7861-3201.jpg?w=996&t=st=1669560720~exp=1669561320~hmac=8efde1a5486603633e5320165f380934b4a8be566b8e200ab47c16dbc2cb9b0e"
}

###
PATCH http://localhost:5555/partners/edit-partner/6383ab1a66ef72d422529822
Content-Type: application/json;

{
    "nama" : "Tasya Aulia,M.Psi.",
    "rate" : "8",
    "overview" : "Tasya Aulia merupakan psikolog pendidikan lulusan Universitas Indonesia.  Tasya mempunyai minat pada isu pola asuh, pendidikan anak usia dini, pengembangan diri, dan masalah remaja. Kasus yang biasa ditangani erat kaitannya dengan parenting dan isu pendidikan. Selain aktif sebagai associate di Ibunda.id,  ia juga aktif sebagai pembicara dalam seminar yang dilakukan online serta menjadi content creator pada instagram Parentsroom, guna psikoedukasi terkait parenting.",
    "pengalaman" : "Psikolog di RS Panama 4 tahun",
    "pendidikan1" : "S-1 Psikologi Universitas Bina Nusantara",
    "pendidikan2" : "S-2 Magister Psikologi Universitas Indonesia",
    "contact" : "089637074190",
    "img" : "https://img.freepik.com/free-photo/smiling-cute-asian-female-doctor-nurse-medical-respirator-rubber-sterile-gloves-looking-pleas_1258-83289.jpg?w=996&t=st=1669187240~exp=1669187840~hmac=bda4bc7e9daf9ef8049685a8f0b480893a52393e0d9fb5cc674f5aa9ec43410e"
}

###
DELETE http://localhost:5555/partners/6383acda66ef72d422529824





###
POST http://localhost:5555/blog/add-blog
Content-Type: application/json;

{
    "img": "https://imgonline.netlify.app/img/page7.png",
    "link": "https://ditsmp.kemdikbud.go.id/mengatasi-perundungan-di-sekolah-dengan-program-roots/"
}

###
GET http://localhost:5555/blog

###
DELETE  http://localhost:5555/blog/6384f4df808b42b4fdf275a6

