GET http://localhost:5555/partners

###
GET http://localhost:5555/partners/63ad9908a472e15d3f47bf59

###
POST http://localhost:5555/partners/add-partner
Content-Type: application/json;

{
    "nama": "Jennie, M. Psi.",
    "rate": "7.5",
    "kota": "Jember",
    "overview": "Putri Citra adalah psikolog yang dapat menangani permasalahan kecemasan dan relasi.Ia yakin bahwa proses kehidupan adalah pencarian jati diri.Membicarakan kekhawatiran kita dengan seorang profesional bisa menjadi langkah yang sangat berarti.",
    "pengalaman": "Psikolog di RS Panama 4 tahun",
    "pendidikan1": "S-1 Psikologi Universitas Atma Jaya Yogyakarta",
    "pendidikan2": "S-2 Psikologi Universitas Negeri Malang",
    "contact": "089637074190",
    "img": "https://img.freepik.com/free-photo/portrait-young-asia-lady-with-positive-expression-arms-crossed-smile-broadly-dressed-casual-clothing-looking-camera-pink-background_7861-3201.jpg?w=996&t=st=1669560720~exp=1669561320~hmac=8efde1a5486603633e5320165f380934b4a8be566b8e200ab47c16dbc2cb9b0e"
}

###
PATCH http://localhost:5555/partners/edit-partner/63bded6ea02405e8a3b831f7
Content-Type: application/json;

{
    "nama": "Sally, M. Psi.",
    "rate": "7.5",
    "kota": "Jember",
    "overview": "Putri Citra adalah psikolog yang dapat menangani permasalahan kecemasan dan relasi.Ia yakin bahwa proses kehidupan adalah pencarian jati diri.Membicarakan kekhawatiran kita dengan seorang profesional bisa menjadi langkah yang sangat berarti.",
    "pengalaman": "Psikolog di RS Panama 4 tahun",
    "pendidikan1": "S-1 Psikologi Universitas Atma Jaya Yogyakarta",
    "pendidikan2": "S-2 Psikologi Universitas Negeri Malang",
    "contact": "089637074190",
    "img": "https://img.freepik.com/free-photo/portrait-young-asia-lady-with-positive-expression-arms-crossed-smile-broadly-dressed-casual-clothing-looking-camera-pink-background_7861-3201.jpg?w=996&t=st=1669560720~exp=1669561320~hmac=8efde1a5486603633e5320165f380934b4a8be566b8e200ab47c16dbc2cb9b0e"
}

###
DELETE http://localhost:5555/partners/63bded6ea02405e8a3b831f7

###
GET http://localhost:5555/partners/lokasi/surabaya

###
GET http://localhost:5555/partners/search/putri




//BLOG

###
POST http://localhost:5555/blog/add-blog
Content-Type: application/json;

{
    "img": "https://imgonline.netlify.app/img/page7.png",
    "link": "https://ditsmp.kemdikbud.go.id/mengatasi-perundungan-di-sekolah-dengan-program-roots/"
}

###
GET http://localhost:5555/blog

###
PATCH http://localhost:5555/blog/edit-blog/638954f1835ca630234c221f
Content-Type: application/json;

{
    "img": "https://imgonline.netlify.app/img/page7.png",
    "link": "https://ditsmp.kemdikbud.go.id/mengatasi-perundungan-di-sekolah-dengan-program-roots/"
}

###
DELETE  http://localhost:5555/blog/638954f1835ca630234c221f



//USER

###
GET http://localhost:5555/users/data-user

###
POST http://localhost:5555/users/register
Content-Type: application/json;

{
    "email": "rafikusdiarto@gmail.com",
    "username": "Rafi Kusdiarto",
    "password": "345bcd"
}

###
POST http://localhost:5555/users/login
Content-Type: application/json;

{
    "username": "m rafi",
    "password": "abc123"
}